- name: create download folder for ipfs-cluster
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    dest: /opt/ipfs-cluster/{{ ipfs_cluster_version }}

- name: download and unpack IPFS Cluster
  when: not ansible_check_mode
  block:
    - name: download IPFS Cluster binaries
      become: yes
      get_url:
        url: "{{ dist_url }}/{{ item }}/{{ ipfs_cluster_version }}/{{ item }}_{{ ipfs_cluster_version }}_linux-{{ ipfs_cluster_arch }}.tar.gz"
        dest: /opt/ipfs-cluster/{{ ipfs_cluster_version }}/{{ item }}.tar.gz
        timeout: 30
      loop:
        - ipfs-cluster-service
        - ipfs-cluster-ctl
   -  name: unpack IPFS Cluster binaries
      become: yes
      unarchive:
        remote_src: yes
        src: /opt/ipfs-cluster/{{ ipfs_cluster_version }}/{{ item }}.tar.gz
        dest: /opt/ipfs-cluster/{{ ipfs_cluster_version }}/
        creates: /opt/ipfs-cluster/{{ ipfs_cluster_version }}/{{ item }}/{{ item }}
      loop:
        - ipfs-cluster-service
        - ipfs-cluster-ctl

- name: remove existing cluster binaries
  file:
    path: /usr/local/bin/{{ item }}
    state: absent
  loop:
    - ipfs-cluster-service
    - ipfs-cluster-ctl
  become: yes
  
- name: link ipfs-cluster executables
  become: yes
  file:
    state: link
    dest: /usr/local/bin/{{ item }}
    src: /opt/ipfs-cluster/{{ ipfs_cluster_version }}/{{ item }}/{{ item }}
  loop:
    - ipfs-cluster-service
    - ipfs-cluster-ctl
  notify: restart IPFS Cluster

- name: make .ipfs-cluster directory
  become: yes
  file:
    state: directory
    mode: 0700
    owner: ipfs
    group: ipfs
    dest: "{{ ipfs_home }}/.ipfs-cluster"

- name: install ipfs-cluster systemd service
  become: yes
  template:
    src: ipfs-cluster.service
    dest: /etc/systemd/system/ipfs-cluster.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart IPFS Cluster

- name: init IPFS Cluster
  become: yes
  become_user: ipfs
  command: ipfs-cluster-service init --consensus crdt
  args:
    creates: "{{ ipfs_home }}/.ipfs-cluster/identity.json"
  environment:
    CLUSTER_PATH: "{{ ipfs_home }}/.ipfs-cluster"

- name: get IPFS Cluster peer ID
  become: yes
  slurp:
    src: "{{ ipfs_home }}/.ipfs-cluster/identity.json"
  register: ipfs_cluster_identity_raw

- name: set IPFS Cluster peer ID fact
  set_fact:
    ipfs_cluster_peer_id: "{{ (ipfs_cluster_identity_raw.content | b64decode | from_json).id }}"
