- name: Ensure acl package is installed
  become: yes
  apt:
    name: acl
    state: present
    update_cache: yes

- name: make ipfs group
  become: yes
  group:
    state: present
    name: ipfs

- name: make ipfs user
  become: yes
  user:
    state: present
    name: ipfs
    group: ipfs
    shell: /bin/false
    home: "{{ ipfs_home }}" # /var/lib/ipfs
    create_home: no         
    comment: IPFS user
    system: yes

- name: create ipfs data directory
  become: yes
  file:
    state: directory
    owner: ipfs
    group: ipfs
    mode: "0750"
    dest: "{{ ipfs_home }}/.ipfs"

- name: create download folder for kubo
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    dest: /opt/kubo/{{ ipfs_version }}

- name: download and unpack IPFS
  when: not ansible_check_mode
  block:
    - name: download IPFS
      become: yes
      get_url:
        url: "{{ dist_url }}/kubo/{{ ipfs_version }}/kubo_{{ ipfs_version }}_linux-{{ ipfs_arch }}.tar.gz"
        dest: /opt/kubo/{{ ipfs_version }}/kubo.tar.gz
        timeout: 30

    - name: unpack kubo
      become: yes
      unarchive:
        remote_src: yes
        src: /opt/kubo/{{ ipfs_version }}/kubo.tar.gz
        dest: /opt/kubo/{{ ipfs_version }}
        creates: /opt/kubo/{{ ipfs_version }}/kubo/ipfs

- name: Remove existing ipfs binary
  become: yes
  file:
    path: /usr/local/bin/ipfs
    state: absent

- name: link kubo executable
  become: yes
  file:
    state: link
    dest: /usr/local/bin/ipfs
    src: /opt/kubo/{{ ipfs_version }}/kubo/ipfs
  notify: restart IPFS
