- name: Ensure acl package is installed
  become: yes
  apt:
    name: acl
    state: present
    update_cache: yes
    
- name: make ipfs group
  become: yes
  group:
    state: present
    name: ipfs