- name: Ensure acl package is installed
  become: yes
  apt:
    name: acl
    state: present
    update_cache: yes

- name: make ipfs group
  become: yes
  group:
    state: present
    name: ipfs

- name: make ipfs user
  become: yes
  user:
    state: present
    name: ipfs
    group: ipfs
    shell: /bin/false
    home: "{{ ipfs_home }}" # /var/lib/ipfs
    create_home: no         
    comment: IPFS user
    system: yes

- name: create ipfs data directory
  become: yes
  file:
    state: directory
    owner: ipfs
    group: ipfs
    mode: "0750"
    dest: "{{ ipfs_home }}/.ipfs"

- name: create download folder for kubo
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    dest: /opt/kubo/{{ ipfs_version }}

- name: download and unpack IPFS
  when: not ansible_check_mode
  block:
    - name: download IPFS
      become: yes
      get_url:
        url: "{{ dist_url }}/kubo/{{ ipfs_version }}/kubo_{{ ipfs_version }}_linux-{{ ipfs_arch }}.tar.gz"
        dest: /opt/kubo/{{ ipfs_version }}/kubo.tar.gz
        timeout: 30

    - name: unpack kubo
      become: yes
      unarchive:
        remote_src: yes
        src: /opt/kubo/{{ ipfs_version }}/kubo.tar.gz
        dest: /opt/kubo/{{ ipfs_version }}
        creates: /opt/kubo/{{ ipfs_version }}/kubo/ipfs

- name: Remove existing ipfs binary
  become: yes
  file:
    path: /usr/local/bin/ipfs
    state: absent

- name: link kubo executable
  become: yes
  file:
    state: link
    dest: /usr/local/bin/ipfs
    src: /opt/kubo/{{ ipfs_version }}/kubo/ipfs
  notify: restart IPFS

- name: install ipfs systemd service
  become: yes
  template:
    src: ipfs.service
    dest: /etc/systemd/system/ipfs.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart IPFS
  tags:
    - init

- name: init IPFS
  become: yes
  become_user: ipfs
  command: ipfs init --profile=server
  args:
    creates: "{{ ipfs_home }}/.ipfs/config"
  environment:
    IPFS_PATH: "{{ ipfs_home }}/.ipfs"

- name: Get IPFS Peer ID
  become: yes
  become_user: ipfs
  command: ipfs id
  register: ipfs_peer_id_output
  changed_when: false
  environment:
    IPFS_PATH: "{{ ipfs_home }}/.ipfs"
  
- name: Set peer ID fact
  set_fact:
    ipfs_peer_id: "{{ (ipfs_peer_id_output.stdout | from_json).ID }}"

- name: Build bootstrap list
  set_fact:
    ipfs_bootstrap_peers: []

- name: Add peers to bootstrap list
  set_fact:
    ipfs_bootstrap_peers: >-
      {{
        ipfs_bootstrap_peers +
        [
          '/ip4/' ~ hostvars[item].ansible_host
          ~ '/tcp/4001/p2p/'
          ~ hostvars[item].ipfs_peer_id
        ]
      }}
  loop: "{{ groups['ipfs_cluster'] }}"
  when: item != inventory_hostname

- name: deploy swarm.key
  become: yes
  become_user: ipfs

  copy:
    content: "{{ ipfs_swarm_key }}"
    dest: "{{ ipfs_home }}/.ipfs/swarm.key"
    owner: ipfs
    group: ipfs
    mode: 0400
  notify: restart IPFS

- debug:
    var: ipfs_bootstrap_peers

# --- config section ---

- name: Configure IPFS Datastore options
  become: yes
  become_user: ipfs
  command: "ipfs config Datastore.{{ item.key }} {{ item.value }} {{ '--json' if item.json | default(false) else '' }}"
  environment:
    IPFS_PATH: "{{ ipfs_home }}/.ipfs"
  loop:
    - { key: 'StorageMax', value: '"{{ ipfs_storage_max | default("60GB") }}"' }
    - { key: 'StorageGCWatermark', value: "{{ ipfs_gc_watermark | default(90) }}", json: true }
    - { key: 'BloomFilterSize', value: "{{ ipfs_bloom_filter_size | default(0) }}", json: true }
    - { key: 'GCPeriod', value: '"{{ ipfs_gc_period | default("1h") }}"' }
  notify: restart IPFS

- name: Configure IPFS Addresses
  become: yes
  become_user: ipfs
  command: "ipfs config Addresses.{{ item.key }} '{{ item.value | to_json }}' --json"
  environment:
    IPFS_PATH: "{{ ipfs_home }}/.ipfs"
  loop:
    - { key: 'API', value: "/ip4/127.0.0.1/tcp/5001" }
    - { key: 'Gateway', value: "/ip4/127.0.0.1/tcp/8080" }
    - { key: 'Swarm', value: ["/ip4/0.0.0.0/tcp/4001", "/ip4/0.0.0.0/udp/4001/quic", "/ip4/0.0.0.0/udp/4001/quic-v1", "/ip6/::/tcp/4001", "/ip6/::/udp/4001/quic", "/ip6/::/udp/4001/quic-v1"] }
  notify: restart IPFS